### ISSUE TITLE
Using the old graph api v1.0 with facebookClient?

### ISSUE THREAD

**Issue by PatrickHuetter** [agorapulse/grails-facebook-sdk#70]
Is it possible to use the old graph api v1.0 with facebookClient? Where can i configure the api base url or version?

I would like to use the old graph api for some requests because the new one is missing some features.

**Comment by Krunalvaghasiya** [comment]
@PatrickHuetter @benorama 

checkins API is deprecated for versions v2.0 and higher

I am getting these error while implementing checkins button .Do not know how to implement . I have tried various solutions . 

Please help .!

Thanks.
