### ISSUE TITLE
Template not found for name [/tags/login-link] and path [/tags/_login-link.gsp]

### ISSUE THREAD

**Issue by andersaa** [agorapulse/grails-facebook-sdk#75]
Hi
I'm using Grails 3.0.4 and org.grails.plugins:facebook-sdk:3.0.1.

After following the installation instructions in the readme in the grails3 branch, I get the following error when I try to create a login link:

Template not found for name [/tags/login-link] and path [/tags/_login-link.gsp]

I copied the templates in /tags/ from the facebook-sdk jar into my /grails-app/views/ and that solved the problem. Is there a problem in the plugin packaging, or am I missing anything in my config?

Anyway, awesome plugin! :)

**Comment by benorama** [comment]
Indeed, it's linked to a Grails bug, since 3.0.2 (should be solved with 3.0.5). You might want to upgrade to the latest version I've released this week: 2.4.0 (which use latest RestFB lib and FB graph API v2.4 by default). Your bug should be solved with this 2.4.0 release.

**Comment by andersaa** [comment]
Awesome, it works!

I had specified facebook-sdk:3.0.1 in my build.gradle, was there ever a 3.0.1 release? Can't find it here now, maybe it was a typo:
http://dl.bintray.com/agorapulse/plugins/org/grails/plugins/facebook-sdk/

Thanks for the quick response!

**Comment by benorama** [comment]
Cool! Yes, I've removed the 3.0.1 to keep a consistent versioning based on FB API version. 2.4.0 is now the official one for Grails3. Have fun!
