### ISSUE TITLE
Latest RestFB 1.18.1

### ISSUE THREAD

**Issue by jalbanesi** [agorapulse/grails-facebook-sdk#77]
Can you upgrade the dependency RestFB to 1.18.1. 
I think I'm having a couple of wrong responses based on this (like exceptions thrown because now deprecated permissions are needed)

**Comment by benorama** [comment]
I've upgraded to grails3 version of the plugin.
Is it the one your are using?

**Comment by jalbanesi** [comment]
I'm using grails 2.5
I just figured that the wrong responses were generated by me =) (I was trying to access a page with the wrong token).
Everything is ok now.

Thanks for the support and this great plugin!
