### ISSUE TITLE
Using the SDK in Grails 3.2.1

### ISSUE THREAD

**Issue by Qsaws** [agorapulse/grails-facebook-sdk#78]
Hi,

i've been trying to add the SDK to my project in order to use the facebook login, but it uses Grails3.2.1 and the doc i found seems to only work for Grails2.

I added compile 'org.grails.plugins:facebook-sdk:2.7.1' to my dependencies in my build.gradle but i don't see where i'm supposed to configure the plugin for the app.id etc, i guess in the application.yml but i don't know how.

Thanks.

**Comment by benorama** [comment]
Indeed, the Grails3 doc for the plugin is not yet up to date.
Have you checked the `grails3` branch README?
https://github.com/agorapulse/grails-facebook-sdk/tree/grails3

**Comment by Qsaws** [comment]
Nope missed that sorry, i ended up here from this page https://plugins.grails.org/plugin/facebook-sdk

Thanks for the help
